# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  create:
    tags:
      - '*.*.*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          npm run build

      - name: test
        run: npm run test:coverage

      - uses: actions/setup-node@v1
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: git fetch origin
      - run: npm --no-git-tag-version version $(git describe --tags --abbrev=0)
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
